import json
import random
from pathlib import Path


def fake_trace():
    points = []
    x, y = 50, 450
    for _ in range(8):
        x += random.randint(10, 40)
        y -= random.randint(20, 60)
        points.append({"x": x, "y": y})
    return points


def fake_sequence():
    moves = ["reach", "dynamic", "match", "bump"]
    holds = ["crimp", "jug", "sloper", "pinch"]
    mods = ["clean", "pause", "retry", "hesitation"]

    seq = []
    for i in range(8):
        seq.append({
            "move": random.choice(moves),
            "hold": random.choice(holds),
            "modifier": random.choice(mods),
            "timestamp": round(i * 0.8, 2)
        })
    return seq


def compile_video(video_path, output_path):
    artifact = {
        "route_name": Path(video_path).stem,
        "location": "unknown",
        "grade": "project",
        "trace": fake_trace(),
        "sequence": fake_sequence(),
        "notes": "generated by prototype compiler"
    }

    with open(output_path, "w") as f:
        json.dump(artifact, f, indent=2)

    return artifact
